name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create artifacts directory
      run: mkdir artifacts

    - name: Copy JAR files
      run: cp target/*.jar artifacts

    - name: List artifacts
      run: ls artifacts

    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-actions-artifact
        path: artifacts
